In [ ]:
import torch
import numpy as np
import matplotlib as plt
import pandas as pd
print(torch.__version__)

2.4.0+cu121


In [ ]:
#Shows us what type of GPUs
!nvidia-smi

Mon Sep 16 16:50:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#scalar
scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[8, 2, 3], [48, 5, 6]] ])
tensor[0]
tensor[1][1][0]

tensor(48)

In [ ]:
tensor = torch.rand(1, 2, 3)
tensor

tensor([[[0.9467, 0.7137, 0.4291],
         [0.4487, 0.4095, 0.1615]]])

In [ ]:
img_tensor = torch.rand(224, 224, 3)
#height, width, color channels
#img_tensor

In [ ]:
zeros = torch.zeros(1,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
ones = torch.ones(1, 2, 3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
listTense = torch.arange(1,100)

In [ ]:
zeros_like = torch.zeros_like(listTense)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

In [ ]:
float32_tens = torch.tensor(listTense, dtype = torch.float32, requires_grad = True, device = None)
float32_tens

<ipython-input-13-875f0a0e9635>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float32_tens = torch.tensor(listTense, dtype = torch.float32, requires_grad = True, device = None)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
        57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70.,
        71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83., 84.,
        85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95., 96., 97., 98.,
        99.], requires_grad=True)

In [ ]:
add_tensor = torch.rand(3, 3, 3)
add_tensor = add_tensor.multiply(10)
add_tensor = add_tensor.subtract(10)
add_tensor = add_tensor.add(10)

In [ ]:
t1 = torch.rand(2, 10)
t2 = torch.rand(10, 10)
torch.matmul(t1, t2)

tensor([[1.5174, 2.3045, 2.0299, 2.9793, 1.6339, 2.8234, 1.7464, 1.9259, 2.0045,
         1.9433],
        [1.5978, 2.1326, 1.5943, 2.4220, 1.2824, 2.8571, 1.4075, 1.7171, 1.9625,
         2.2179]])

In [ ]:
tester = torch.rand(3, 3)
tester

tensor([[0.4343, 0.6382, 0.0085],
        [0.3151, 0.3251, 0.8740],
        [0.1136, 0.9190, 0.2367]])